### ISSUE TITLE
Bug na abertura de empresa/cadastrar.xhtml

### ISSUE THREAD

**Issue by fabriciofx** [ifpeppo/empregoja#31]
Corrigir o path dos arquivos a serem incluidos.

/Empresa/Cadastrar.xhtml @18,39 <ui:include src="menu.xhtml"> Invalid path : menu.xhtml

**Comment by leonardoanselmo** [comment]
Fabricio, corrigir o path, mesmo assim não consigo abrir o projeto no navegador. Seria possivel olha onde estou errando. Ele consegue abrir individualmente. Vlw
